### ISSUE TITLE
Error while trying demo docker with BRCA-US

### ISSUE THREAD

**Issue by pieterlukasse** [icgc-dcc/dcc-cm#11]
I got an error while trying the steps in https://github.com/icgc-dcc/dcc-cm/tree/develop/docker/dcc-portal-demo for BRCA-US project.

Steps I executed:
```
sudo docker run -v /media/pieter/b250/data-icgc:/mnt/dcc_data -it --rm icgcdcc/dcc-portal-demo import -p BRCA-US
```
Output:
```
Checking the data dir configuration...
Checking if data volume is mounted...
Downloading data...
--2017-08-31 10:34:53--  https://download.icgc.org/exports/repository.tar.gz
Resolving download.icgc.org (download.icgc.org)... 206.108.121.80
Connecting to download.icgc.org (download.icgc.org)|206.108.121.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘repository.tar.gz’

repository.tar.gz             [              <=>                    ]  68.89M  11.2MB/s   in 11s    

2017-08-31 10:35:04 (6.12 MB/s) - ‘repository.tar.gz’ saved [72237383]

--2017-08-31 10:35:04--  https://download.icgc.org/exports/data.open.tar?project=BRCA-US
Resolving download.icgc.org (download.icgc.org)... 206.108.121.80
Connecting to download.icgc.org (download.icgc.org)|206.108.121.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-tar]
Saving to: ‘data.open.tar’

data.open.tar                 [                     <=>             ]   5.90G  6.59MB/s   in 18m 3s 

2017-08-31 10:53:08 (5.58 MB/s) - ‘data.open.tar’ saved [6336296960]

--2017-08-31 10:53:08--  https://download.icgc.org/exports/release.tar
Resolving download.icgc.org (download.icgc.org)... 206.108.121.80
Connecting to download.icgc.org (download.icgc.org)|206.108.121.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-tar]
Saving to: ‘release.tar’

release.tar                   [       <=>                           ]  56.14G   986KB/s   in 15h 57m 

2017-09-01 02:50:48 (1.00 MB/s) - ‘release.tar’ saved [60277145600]

Importing download data...
Finished importing download data.
[....] Starting Elasticsearch Server:sysctl: setting key "vm.max_map_count": Read-only file system
. ok 
Importing the repository.tar.gz...
2017-09-01 02:52:27,190 [main] INFO  o.i.d.d.i.ClientMain - ----------------------------------------------------------------------------------------------------
2017-09-01 02:52:27,192 [main] INFO  o.i.d.d.i.ClientMain - Running with ClientOptions(inputFile=/mnt/dcc_data/tmp/repository.tar.gz, esUrl=es://localhost:9300, project=null, version=false, help=false)
2017-09-01 02:52:27,192 [main] INFO  o.i.d.d.i.ClientMain - ----------------------------------------------------------------------------------------------------
2017-09-01 02:52:27,195 [main] INFO  o.i.d.d.i.c.IndexClientCommand - Creating tar reader for file /mnt/dcc_data/tmp/repository.tar.gz
2017-09-01 02:52:27,250 [main] INFO  o.i.d.r.j.i.f.TransportClientFactory - Creating ES transport client from URI 'es://localhost:9300': host = 'localhost', port = 9300
2017-09-01 02:52:27,839 [main] INFO  o.i.d.d.c.e.DocumentWriterFactory - Creating ES transport client from URI 'es://localhost:9300': host = 'localhost', port = 9300
2017-09-01 02:52:28,060 [main] INFO  o.i.d.d.c.e.i.DefaultDocumentWriter - [1899476638] Created ES document writer.
2017-09-01 02:52:28,077 [main] INFO  o.i.d.d.i.s.IndexService - Checking index 'icgc-repository-20170726' for existence...
2017-09-01 02:52:28,082 [main] INFO  o.i.d.d.i.s.IndexService - Creating index 'icgc-repository-20170726'...
2017-09-01 02:52:29,835 [main] INFO  o.i.d.d.i.s.IndexService - Creating index 'icgc-repository-20170726' mapping for type 'repository'...
2017-09-01 02:52:29,937 [main] INFO  o.i.d.d.i.s.IndexService - Creating index 'icgc-repository-20170726' mapping for type 'file-centric'...
2017-09-01 02:52:30,173 [main] INFO  o.i.d.d.i.s.IndexService - Creating index 'icgc-repository-20170726' mapping for type 'file-text'...
2017-09-01 02:52:30,208 [main] INFO  o.i.d.d.c.e.i.DefaultDocumentWriter - [1899476638] Closing bulk processor...
2017-09-01 02:52:30,223 [main] INFO  o.i.d.d.c.e.i.DefaultDocumentWriter - [1899476638] Finished indexing 0 documents
2017-09-01 02:52:30,224 [main] ERROR o.i.d.d.i.ClientMain - Unknown error: 
org.elasticsearch.index.mapper.MapperParsingException: No handler for type [keyword] declared on field [donor_id]
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:288)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:214)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:189)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:290)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:214)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:136)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:209)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:190)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:444)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:505)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:352)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:184)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Unknow error. Please check the log for detailed error messages: No handler for type [keyword] declared on field [donor_id]
```

**Comment by pieterlukasse** [comment]
Just tried with `PACA-CA` study (which is the example given in the documentation), and got the same error.

```
org.elasticsearch.index.mapper.MapperParsingException: No handler for type [keyword] declared on field [donor_id]
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:288)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:214)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:189)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:290)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:214)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:136)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:209)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:190)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:444)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:505)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:352)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:184)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Unknow error. Please check the log for detailed error messages: No handler for type [keyword] declared on field [donor_id]
```

**Comment by pieterlukasse** [comment]
maybe related to this one: https://discuss.icgc.org/t/failed-to-import-repository-tar-gz-using-dcc-download-import-jar-recently/126

**Comment by andricDu** [comment]
I've updated the image with the new elasticsearch, you can give it a try.

**Comment by pieterlukasse** [comment]
thanks @andricDu , that seems to have solved the error I reported here :+1:
